version: '3.3'

services:
  frontend:
    build:
      context: ./Front-End
      dockerfile: Dockerfile
#    image: frontend
    container_name: front
    ports:
      - 3000:3000
    depends_on:
      - backend
  backend:
    build: 
       context: ./Back-End
       dockerfile: Dockerfile
#    image: go
    container_name: back
    command: sh -c "while true; do sleep 1; done"
    #command: sh -c "./Back-End/Back-End"
    ports:
      - 8000:8000
    depends_on:
      - mysql
  mysql:
    build:
       context: ./DockerfileDB
       dockerfile: Dockerfile
#    image: mysql
    container_name: mysqlDB
    restart: always
    ports:
      - 3306:3306
