version: '3.3'

services:
  frontend:
    image: frontend
    container_name: front
    ports:
      - 3000:3000
    depends_on:
      - backend
  backend:
    image: go
    container_name: back
    ports:
      - 8000:8000
    depends_on:
      - mysql
  mysql:
    image: mysql
    container_name: mysqlDB
    restart: always
    container_name: 172.23.0.2
    ports:
      - 3306:3306
